Resources:
  PatientsDynamoDbTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "patientId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "patientId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: accountIdIndex
          KeySchema:
            - AttributeName: patientId
              KeyType: "HASH"
            - AttributeName: accountId
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      TableName: ${file(./sls/variables.yml):${self:provider.stage}.PATIENTS_TABLE}
  PatientNotesDynamoDbTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "patientId"
          AttributeType: "S"
        - AttributeName: "noteId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "patientId"
          KeyType: "HASH"
        - AttributeName: "noteId"
          KeyType: "RANGE"
      TableName: ${file(./sls/variables.yml):${self:provider.stage}.PATIENT_NOTES_TABLE}
